/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package shopbillingsystem;

import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class ChangePassword extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public ChangePassword() {
        initComponents();
        con = new NewClass().connect();
        p3.setVisible(false);
        t3.setVisible(false);
        b3.setVisible(false);
    }

    public void sign() {

        String username = t1.getText();
        String password = t2.getText();
        massege.setText("");

        try {

            pst = con.prepareStatement("SELECT * FROM login WHERE username='" + username + "'");
            rs = pst.executeQuery();
            rs.next();
            String p = rs.getString("password");

            if (password.equals(p)) {
                int dialog = JOptionPane.showConfirmDialog(null, "LOGIN SUCCESSFUL");
                if (dialog == 0) {

                    p3.setVisible(true);
                    t3.setVisible(true);
                    b3.setVisible(true);
                    t1.setEditable(false);
                    t2.setEditable(false);

                }
            } else {
                massege.setText("Something Went Wrong");
                p3.setVisible(false);
                t3.setVisible(false);
                b3.setVisible(false);
            }

        } catch (Exception e) {
            massege.setText("Something Went Wrong");
            p3.setVisible(false);
            t3.setVisible(false);
            b3.setVisible(false);
        }
    }

    public void update() {

        try {
            if (!"".equals(t3.getText())) {
                int dialog = JOptionPane.showConfirmDialog(null, "ARE YOU SURE ?");
                if (dialog == 0) {
                    pst = con.prepareStatement("UPDATE login SET password='" + t3.getText() + "' WHERE username='" + t1.getText() + "'");
                    pst.execute();
                    t3.setText("");
                    p3.setVisible(false);
                    t3.setVisible(false);
                    b3.setVisible(false);
                    t1.setEditable(true);
                    t2.setEditable(true);
                    t1.setText("");
                    t2.setText("");

                }
            }

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        p3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        massege = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 71, 30));

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 40, 224, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 82, 71, 30));

        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 82, 224, 30));

        p3.setForeground(new java.awt.Color(0, 0, 0));
        p3.setText("New password");
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 213, 89, 30));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 213, 224, 30));

        massege.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(massege, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 130, 285, 25));

        b3.setBackground(new java.awt.Color(51, 51, 255));
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("UPDATE");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 274, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 170));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 20, 90));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        if (evt.getKeyCode() == 10) {
            t2.requestFocus();
        }
    }//GEN-LAST:event_t1KeyPressed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
        if (evt.getKeyCode() == 10) {
            sign();
        }
    }//GEN-LAST:event_t2KeyPressed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        update();
    }//GEN-LAST:event_b3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel massege;
    private javax.swing.JLabel p3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
