/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shopbillingsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class statement extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public statement() {
        initComponents();
        con = new NewClass().connect();
        accountBalance();
        
    }

    public Double debit(String tablename) {

        try {
            pst = con.prepareStatement("SELECT SUM(DebitRs) FROM " + tablename);
            rs = pst.executeQuery();
            rs.next();
            return rs.getDouble("SUM(DebitRs)");

        } catch (Exception e) {
            return 0.0;
        }
    }
    
    
    public Double credit(String tablename) {

        try {
            pst = con.prepareStatement("SELECT SUM(CreditRs) FROM " + tablename);
            rs = pst.executeQuery();
            rs.next();
            return rs.getDouble("SUM(CreditRs)");

        } catch (Exception e) {
            return 0.0;
        }
    }
    
    
    public void accountBalance(){
        Double x1=debit("cashaccount")-credit("cashaccount");
        Double x2=debit("purchaseaccount")-credit("purchaseaccount");
        Double x3=debit("debtorsaccount")-credit("debtorsaccount");
        d1.setText(Double.toString(x1));
        d2.setText(Double.toString(x2));
        d3.setText(Double.toString(x3));
        t1.setText(Double.toString(x1+x2+x3));
        
        Double x6=credit("creditorsaccount")-debit("creditorsaccount");
        c6.setText(Double.toString(x6));
        t3.setText(Double.toString(x6));
        
        Double x7=credit("incomeaccount")-debit("incomeaccount");
        c7.setText(Double.toString(x7));
        
        Double x8=debit("expensesaccount")-credit("expensesaccount");
        d8.setText(Double.toString(x8));
        
        t4.setText(Double.toString(x7-x8));
        
        Double x4=credit("capitalaccount")-debit("capitalaccount");
        Double x5=credit("drawingsaccount")-debit("drawingsaccount");
        c4.setText(Double.toString(x4));
        c5.setText(Double.toString(x5));
        t2.setText(Double.toString(x4+x5+x7-x8));
        
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("×");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        jLabel23.setText("ACCOUNT STATEMENT");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 280, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Credit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 50, 30));

        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 160, 30));

        d1.setForeground(new java.awt.Color(255, 255, 255));
        d1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cash Book");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 110, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Debit");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 50, 30));

        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 160, 30));

        d2.setForeground(new java.awt.Color(255, 255, 255));
        d2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Purchase Account");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 110, 30));

        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 160, 30));

        d3.setForeground(new java.awt.Color(255, 255, 255));
        d3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Debtors Account");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 110, 30));

        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 160, 30));

        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 160, 30));

        d4.setForeground(new java.awt.Color(255, 255, 255));
        d4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 160, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capital Account");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 110, 30));

        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 160, 30));

        d5.setForeground(new java.awt.Color(255, 255, 255));
        d5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 160, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Drawings Account");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 110, 30));

        c5.setForeground(new java.awt.Color(255, 255, 255));
        c5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 160, 30));

        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 160, 30));

        d6.setForeground(new java.awt.Color(255, 255, 255));
        d6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Creditors Account");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 110, 30));

        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 160, 30));

        c7.setForeground(new java.awt.Color(255, 255, 255));
        c7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 160, 30));

        d7.setForeground(new java.awt.Color(255, 255, 255));
        d7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 160, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Income Account");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 110, 30));

        t4.setForeground(new java.awt.Color(255, 255, 255));
        t4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 160, 30));

        d8.setForeground(new java.awt.Color(255, 255, 255));
        d8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 160, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Assets            =");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 130, 30));

        c8.setForeground(new java.awt.Color(255, 255, 255));
        c8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 160, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Expenses Account");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 110, 30));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Profit / Loss         =");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 120, 30));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Liabilities        =");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 130, 30));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Equities          =");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Inquiry.jButton1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    // End of variables declaration//GEN-END:variables
}
